#ifndef __CallTransferDlgImpl__
#define __CallTransferDlgImpl__

/**
@file
Subclass of CallTransferDlg, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

/** Implementing CallTransferDlg */
class CallTransferDlgImpl : public CallTransferDlg
{
public:
	/** Constructor */
	CallTransferDlgImpl( wxWindow* parent );

	wxString GetDestNum();
};

#endif // __CallTransferDlgImpl__
