#ifndef __CallPopupDlgImpl__
#define __CallPopupDlgImpl__

/**
@file
Subclass of CallPopupDlg, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

/** Implementing CallPopupDlg */
class CallPopupDlgImpl : public CallPopupDlg
{
private:
    wxWindow* m_parentPtr;
    wxTimer m_timer;
    wxUint8 m_timerCnt;
    bool m_isActiveMsg;

    /// 팝업창 위치와 크기 지정 변수
    wxUint16 m_posX;
    wxUint16 m_posY;
    wxUint16 m_sizeWidth;
    wxUint16 m_sizeHeight;

protected:
	// Handlers for CallPopupDlg events.
	void OnClose( wxCloseEvent& event );
	void OnInitDialog( wxInitDialogEvent& event );
    void OnLeftDown( wxMouseEvent& event );
    void HideDialog();
    void ShowDialog();
    void OnTimerEvent(wxTimerEvent& event);

public:
	/** Constructor */
	CallPopupDlgImpl( wxWindow* parent );

    void ShowMessage(const wxString& msg, const wxString& title = _("알려드립니다."));

	DECLARE_EVENT_TABLE()
};

#endif // __CallPopupDlgImpl__
