#ifndef __CreateSessionDlgImpl__
#define __CreateSessionDlgImpl__

/**
@file
Subclass of CreateSessionDlg, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

/** Implementing CreateSessionDlg */
class CreateSessionDlgImpl : public CreateSessionDlg
{
protected:
	// Handlers for CreateSessionDlg events.
	//void OnButtonClick_Connect( wxCommandEvent& event );
	//void OnButtonClick_Cancel( wxCommandEvent& event );

public:
	/** Constructor */
	CreateSessionDlgImpl( wxWindow* parent );
	wxString GetHostname();
	wxString GetPort();
	wxString GetAmiId();
	wxString GetAmiPw();
	wxString GetExten();

    void SetHostname(const wxString& str);
	void SetPort(const wxString& str);
	void SetAmiId(const wxString& str);
	void SetAmiPw(const wxString& str);
	void SetExten(const wxString& str);
};

#endif // __CreateSessionDlgImpl__
