#ifndef __MakeCallDlgImpl__
#define __MakeCallDlgImpl__

/**
@file
Subclass of MakeCallDlg, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

/** Implementing MakeCallDlg */
class MakeCallDlgImpl : public MakeCallDlg
{
public:
	/** Constructor */
	MakeCallDlgImpl( wxWindow* parent );

	wxString GetDestNum();
	wxString GetSourceNum();

	void SetSourceNum(const wxString& str);
};

#endif // __MakeCallDlgImpl__
